-- ============================================
-- Seed: 60 booking-ticker entries (all active)
-- ============================================
-- One-time bulk seed for the homepage social-proof ticker (ticker_bookings).
-- Run once in the Supabase SQL editor. NOT idempotent — running it again
-- will duplicate all 60 rows (no unique constraint besides the auto id).

INSERT INTO ticker_bookings
  (guest_first_name, guest_city, service_label, service_type, real_booking_date, is_active)
VALUES
  ('Amit S.', 'Delhi', 'Nainital Darshan', 'day_tour', '2026-08-01', true),
  ('Priya K.', 'Gurgaon', 'Kathgodam ➝ Nainital transfer', 'transfer', '2026-07-29', true),
  ('Rahul M.', 'Noida', '4 Days Kumaon Tour', 'multi_day_rental', '2026-08-02', true),
  ('Neha G.', 'Lucknow', 'Lake Tour + Kainchi Dham', 'day_tour', '2026-07-31', true),
  ('Vikas T.', 'Delhi', 'Delhi ➝ Nainital transfer', 'transfer', '2026-07-28', true),
  ('Pooja R.', 'Ghaziabad', 'Mukteshwar Day Tour', 'day_tour', '2026-07-25', true),
  ('Gaurav H.', 'Kanpur', '3 Days Nainital & Bhimtal', 'multi_day_rental', '2026-08-01', true),
  ('Ritu V.', 'Gurgaon', 'Nainital ➝ Delhi transfer', 'transfer', '2026-07-30', true),
  ('Manish D.', 'Agra', 'Ranikhet Day Tour', 'day_tour', '2026-08-02', true),
  ('Sneha L.', 'Delhi', 'Nainital Local Sightseeing', 'day_tour', '2026-07-26', true),
  ('Arun P.', 'Gurgaon', '5 Days Nainital-Corbett', 'multi_day_rental', '2026-07-27', true),
  ('Megha S.', 'Delhi', 'Kathgodam ➝ Nainital transfer', 'transfer', '2026-07-29', true),
  ('Tarun B.', 'Noida', 'Kainchi Dham Darshan', 'day_tour', '2026-08-01', true),
  ('Kriti J.', 'Delhi', '2 Days Nainital Getaway', 'multi_day_rental', '2026-08-02', true),
  ('Rohit K.', 'Meerut', 'Bhimtal & Naukuchiatal Tour', 'day_tour', '2026-07-30', true),
  ('Anjali M.', 'Gurgaon', 'Nainital Darshan', 'day_tour', '2026-07-31', true),
  ('Vivek C.', 'Delhi', '4 Days Nainital & Ranikhet', 'multi_day_rental', '2026-07-28', true),
  ('Divya N.', 'Lucknow', 'Cave Garden & Himalaya View', 'day_tour', '2026-08-01', true),
  ('Sourav D.', 'Kolkata', 'Nainital Darshan', 'day_tour', '2026-08-02', true),
  ('Riya S.', 'Siliguri', '5 Days Nainital-Corbett', 'multi_day_rental', '2026-08-01', true),
  ('Arindam M.', 'Howrah', 'Kathgodam ➝ Nainital transfer', 'transfer', '2026-07-31', true),
  ('Ananya B.', 'Kolkata', 'Lake Tour + Kainchi Dham', 'day_tour', '2026-07-29', true),
  ('Tanmay C.', 'Durgapur', '4 Days Kumaon Tour', 'multi_day_rental', '2026-07-28', true),
  ('Puja G.', 'Kolkata', 'Nainital Local Sightseeing', 'day_tour', '2026-08-02', true),
  ('Debashis B.', 'Asansol', '3 Days Nainital & Bhimtal', 'multi_day_rental', '2026-07-30', true),
  ('Shreya M.', 'Kolkata', 'Nainital ➝ Kathgodam transfer', 'transfer', '2026-08-01', true),
  ('Aritra N.', 'Howrah', 'Mukteshwar Day Tour', 'day_tour', '2026-07-27', true),
  ('Sneha D.', 'Kolkata', 'Ranikhet Day Tour', 'day_tour', '2026-07-26', true),
  ('Pratik B.', 'Haldia', '4 Days Nainital & Ranikhet', 'multi_day_rental', '2026-08-02', true),
  ('Moumita S.', 'Kolkata', 'Kainchi Dham Darshan', 'day_tour', '2026-07-31', true),
  ('Subhajit R.', 'Siliguri', '5 Days Nainital-Kausani', 'multi_day_rental', '2026-07-29', true),
  ('Ritika C.', 'Kolkata', 'Bhimtal & Naukuchiatal Tour', 'day_tour', '2026-08-01', true),
  ('Suman G.', 'Durgapur', 'Kathgodam ➝ Nainital transfer', 'transfer', '2026-07-28', true),
  ('Piyali M.', 'Kolkata', '3 Days Nainital Getaway', 'multi_day_rental', '2026-08-02', true),
  ('Abhijit S.', 'Asansol', 'Nainital Darshan', 'day_tour', '2026-07-30', true),
  ('Nandini K.', 'Kolkata', 'Cave Garden & Himalaya View', 'day_tour', '2026-07-25', true),
  ('Hardik P.', 'Ahmedabad', 'Nainital Darshan', 'day_tour', '2026-08-01', true),
  ('Jinal S.', 'Surat', '4 Days Kumaon Tour', 'multi_day_rental', '2026-08-02', true),
  ('Parth J.', 'Vadodara', 'Delhi ➝ Nainital transfer', 'transfer', '2026-07-31', true),
  ('Hiral M.', 'Rajkot', 'Lake Tour + Kainchi Dham', 'day_tour', '2026-07-30', true),
  ('Jigar D.', 'Ahmedabad', '5 Days Nainital-Corbett', 'multi_day_rental', '2026-07-29', true),
  ('Krunal T.', 'Surat', 'Mukteshwar Day Tour', 'day_tour', '2026-08-02', true),
  ('Dhruv B.', 'Ahmedabad', 'Nainital Local Sightseeing', 'day_tour', '2026-07-28', true),
  ('Binal R.', 'Gandhinagar', '3 Days Nainital & Bhimtal', 'multi_day_rental', '2026-07-27', true),
  ('Meet V.', 'Surat', 'Kathgodam ➝ Nainital transfer', 'transfer', '2026-08-01', true),
  ('Nidhi P.', 'Ahmedabad', 'Ranikhet Day Tour', 'day_tour', '2026-07-31', true),
  ('Chirag K.', 'Vadodara', '4 Days Nainital & Ranikhet', 'multi_day_rental', '2026-08-02', true),
  ('Riddhi G.', 'Rajkot', 'Kainchi Dham Darshan', 'day_tour', '2026-07-30', true),
  ('Swapnil D.', 'Mumbai', 'Nainital Darshan', 'day_tour', '2026-08-02', true),
  ('Rutuja P.', 'Pune', '5 Days Nainital-Corbett', 'multi_day_rental', '2026-08-01', true),
  ('Omkar S.', 'Nagpur', 'Kathgodam ➝ Nainital transfer', 'transfer', '2026-07-29', true),
  ('Snehal K.', 'Mumbai', 'Lake Tour + Kainchi Dham', 'day_tour', '2026-07-31', true),
  ('Kedar J.', 'Nashik', '4 Days Kumaon Tour', 'multi_day_rental', '2026-07-28', true),
  ('Prachi M.', 'Pune', 'Mukteshwar Day Tour', 'day_tour', '2026-07-30', true),
  ('Kartik R.', 'Bangalore', 'Nainital Local Sightseeing', 'day_tour', '2026-08-02', true),
  ('Swati N.', 'Hyderabad', 'Delhi ➝ Nainital transfer', 'transfer', '2026-08-01', true),
  ('Ramesh K.', 'Chennai', 'Ranikhet Day Tour', 'day_tour', '2026-07-31', true),
  ('Simran K.', 'Chandigarh', '3 Days Nainital & Bhimtal', 'multi_day_rental', '2026-07-30', true),
  ('Vikram S.', 'Jaipur', 'Kathgodam ➝ Nainital transfer', 'transfer', '2026-07-29', true),
  ('Neeraj G.', 'Bhopal', 'Kainchi Dham Darshan', 'day_tour', '2026-08-02', true);
